name: ctfp
version: '1.0.0'
synopsis: Solutions to problems in /Category Theory for Programmers/.
description: Solutions to problems in /Category Theory for Programmers/.
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.8 && < 4.11
  - text >= 1.2 && < 1.3

library:
  source-dirs: lib
